#ifndef __BINDINGSJS_GENERATEDPLUS_HJSCOCOS2DXSTUDIOPLUS_H__
#define __BINDINGSJS_GENERATEDPLUS_HJSCOCOS2DXSTUDIOPLUS_H__

#include "jsapi.h"

void register_HJSCocos2dxStudioPlus(JSContext *cx, JSObject *global);

#endif // __BINDINGSJS_GENERATEDPLUS_HJSCOCOS2DXSTUDIOPLUS_H__
