#ifndef __BINDINGSJS_GENERATEDPLUS_HJSCOCOS2DXGUIPLUS_H__
#define __BINDINGSJS_GENERATEDPLUS_HJSCOCOS2DXGUIPLUS_H__

#include "jsapi.h"

void register_HJSCocos2dxGUIPlus(JSContext *cx, JSObject *global);

#endif // __BINDINGSJS_GENERATEDPLUS_HJSCOCOS2DXGUIPLUS_H__
